### ISSUE TITLE
ESP32: DAC does not seem to work

### ISSUE THREAD

**Issue by rovale** [espruino/Espruino#1574] opened 2018-11-29 10:44 UTC
It seems DAC does not work on the espruino_2v00_esp32.

Goal: dim an LED using the `analogWrite(D26, 0.5)` command.

Expected behaviour: LED dims to about 50%.

Actual behaviour: LED dims to about 0%. No light.

Tag: ESP32

Discussion: http://forum.espruino.com/conversations/328147/

**Comment by swineone** [comment] 2019-04-22 16:40
That’s not how LEDs work. You’re assuming they’re linear devices, but they’re not. There’s no reason not to stick to PWM in this case. The DAC probably is unable to supply enough current to light the LED properly at above, say, 25% of its typical current.

I suggest closing this as it’s definitely not a bug in Espruino.

**Closed** 2019-04-23 06:06 UTC
Labels: ESP32
