### ISSUE TITLE
Pressing Enter anywhere but EOL breaks statement

### ISSUE THREAD

**Issue by morganrallen** [espruino/Espruino#471] opened 2015-01-05 20:00 UTC
Happens when either editing history or correcting something in the current line.

![linebreak bug](http://mra.xen.prgmr.com/espruino_linebreak.gif)

**Comment by gfwilliams** [comment] 2015-01-06 07:41
Thanks for the video... How did you record it?

I think this is actually the behaviour you'd expect - unless I'm missing something. How else would you add a newline to an existing statement? To execute immediately, just hit 'end' or 'page down' to go to the end of the line - and if you did it by accident then just press backspace to delete the newline.

**Comment by morganrallen** [comment] 2015-01-06 07:47
Shot with a program called SimpleScreenRecorder, converted to gif with
ffmpeg and compress with ImageMagick.

The behavior I would expect it pressing Enter would submit the statement,
while Shift-Enter would insert the line break. This is also in line with
DevTools.

On Mon, Jan 5, 2015 at 11:41 PM, Gordon Williams <notifications@github.com>
wrote:

> Thanks for the video... How did you record it?
>
> I think this is actually the behaviour you'd expect - unless I'm missing
> something. How else would you add a newline to an existing statement? To
> execute immediately, just hit 'end' or 'page down' to go to the end of the
> line - and if you did it by accident then just press backspace to delete
> the newline.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/espruino/Espruino/issues/471#issuecomment-68835440>.
>



-- 
http://ithoughtyouweretherobot.com
Metal and Wire

http://nolonelyguineapigs.com/
Wandering and Rambling

http://morglog.org
Old and Neglected.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20121007
Comment: http://openpgpjs.org

xsBNBFG3btUBB/9+/WJNOSIuc/praKPaPOweqXV5s7PGRD+HAnNWF/19YAY3
AFtfeoelhhY4sMJoobTaJzcZojznZ1kl/7UuuYCnbJO3Z9kaSMVrVxEZMSLe
YmW8Hc4ZsTnl9f05DQFy8ABpAvMLmXJQXh63BbfzjFqNbSWQfLhrubSM2Elq
xmN6EsmRyAuEeYlSnal+Di2MlViohpCbbagE2D6AZTUECIamTib6+DuLG4XO
b4GGKHR9TXu2qS1VH6hqcvdEz2MDE5OqZzAnBgcF2dvcOdTk9gAOoR1T+qKj
IJtg2X0ETbxcPqEXQoXE8VrxN0MLT5JQKTg26+csU4P2w0rEWsUsJombABEB
AAHNJU1vcmdhbiBBbGxlbiA8bW9yZ2FucmFsbGVuQGdtYWlsLmNvbT7CwFwE
EAECABAFAlG3btwJEG9pFLKaVEfeAAD7hwf+K8LN/kfgi8GTRLiTcuM+hSbm
uAeiBY+VaJIQFLzoFlt8A0hBlLNPFNNmUDxdPrMErdHgZ7HtJW/6RANuBTti
5hr3EBguH1GQyK7BbUqJGvaEX4UNRej3uyX3ufXDsIB/3NsKaTyyu+SO0+Hv
Cn2DwmlfSXcPhoarx6Turizn/WwgtTN3tqrMWxxiCKWydLH5xYuz+23BLMdc
oF/zkbF+7ddFhmyfiFh4Ej9//tsfwPj2cACU3uLTrcwCo7IxUtkrqMF/fhlm
LEqjhzDDjq9v7GNWb/5xB2xgTaucJ7/ljuS8nPlZqwCI8NlTgSqC8nyVLyjS
yVtOzkItcS0UqyW1Mg==
=V/Ia
-----END PGP PUBLIC KEY BLOCK-----

**Comment by gfwilliams** [comment] 2015-01-06 09:15
Thanks! It could be pretty handy.

In terms of the newline, I'm not sure there's much of a standard. node.js's console works differently  and seems to basically ignore shift-enter completely and inserts a newline if it considers that the statement isn't complete - which doesn't seem great.

I'd be interested to see what others think about this? the enter to execute, shift-enter for newline makes a lot of sense - but I wonder if it'd confuse existing users, and the existing way is very easy to use when you get used to it. Espruino has been around for 3 years now and this is the first time anyone's actually complained.

**Comment by AlexanderBrevig** [comment] 2015-01-15 15:03
For some reason this also bugged me in the beginning (I think it's because I'm used to the Chrome Console as a JS REPL. This console treats `Enter` as a 'submit the current buffer to the REPL' rather than 'insert a new line into buffer').

I'm used to pressing `PgDn`, `Enter` now though - and I prefer it. 

During REPL prototyping it's nice to be able to write code as you normally do (I.e no shift enter) and then just `PgDn`, `Enter` when the code is ready.

**Comment by gfwilliams** [comment] 2015-05-01 14:42
Closing this - not a bug, and nobody else seems to think it's really a problem. I fact I bet I'd get complaints if I changed it now :)

**Closed by gfwilliams** 2015-05-01 14:42 UTC
