### ISSUE TITLE
Cannot "turn off" Banglejs after flashing 2v09

### ISSUE THREAD

**Issue by bernhardreiter** [espruino/Espruino#2023] opened 2021-07-11 11:10 UTC
Having flashed  a watch from 2v08 to 2v09 (following the instructions and shown in the about infos), now I cannot turn the watch off.

* Selecting "Settings", 
*  selecting "turn off" from the last but one entry.
* press BTN2

Observation: The clock does a "reset",
it says "sw reset" and "DFU ZY08" and is back to the main sceen with the clock.

Expectation: screen stays black, just is did before flashing

Side observation: subjectively I'd say that buttons were a little less responsive after flashing.

**Comment by gfwilliams** [comment] 2021-07-11 17:35
Thanks - I'll look into this. I'm on holiday the next 2 weeks though and if you need to turn off you should be able to do so through the bootloader (hold btn1+2 for around 10 seconds). It's possible it is already fixed in 'cutting edge' builds though.

**Comment by bernhardreiter** [comment] 2021-07-12 07:31
@gfwilliams thanks for the hint and have nice holidays.

**Comment by kuleszdl** [comment] 2021-07-31 10:39
@bernhardreiter Did you reset something after updating to 2v09? For me, turning off used to work in 2v09, however, I resetted all apps and settings after updating the firmware.

**Comment by bernhardreiter** [comment] 2021-08-01 10:23
> Did you reset something after updating to 2v09? 

No. (Should I have done so? Do not remember this from the flashing instructions.)

**Comment by gfwilliams** [comment] 2021-08-02 10:56
There was actually a firmware change, so 'turn off' did `Bangle.softOff` and not `Bangle.off`.

If you also updated everything using the app loader, it's possible that `Bangle.softOff` actually works fine on 2v09 so everything would be ok.

**Comment by bernhardreiter** [comment] 2021-08-02 13:44
As far as I remember I did update everything I could with the app loader and afterwards had the problem. I'll recheck next time.

**Comment by gfwilliams** [comment] 2021-08-13 10:44
I can't reproduce this with new firmwares - they seem to work fine - so closing with 2v10 release.

**Closed by gfwilliams** 2021-08-13 10:44 UTC
