### ISSUE TITLE
ESP32: https request no longer works

### ISSUE THREAD

**Issue by wilberforce** [espruino/Espruino#1613] opened 2019-02-04 03:30 UTC
See:

http://forum.espruino.com/conversations/330049/#comment14604279

```
var http = require("http");
http.get("https://www.google.com", function(res) {
  res.on('data', function(data) {
    console.log(data);
  });
});
```

```
Uncaught InternalError: Failed! mbedtls_ssl_setup: Not enough memory
```

**Comment by GabrielGab** [comment] 2019-02-09 22:55
yes ,confirm , no longer works, on version 2.01 for ES32

**Comment by wilberforce** [comment] 2019-02-12 06:15
```
>process.env
={
  "VERSION": "1v98",
  "GIT_COMMIT": "1e06400",
  "BOARD": "ESP32",
  "FLASH": 0, "RAM": 524288,
  "SERIAL": "240ac400-2f90",
  "CONSOLE": "Serial1",
  "MODULES": "Flash,Storage,fs," ... "r,crypto,neopixel",
  "EXPTR": 1073485304 }
>ESP32.getState()
={
  "sdkVersion": "v3.0",
  "freeHeap": 37668 }
>

```

**Comment by wilberforce** [comment] 2019-02-12 10:12
Got this working by reducing jsvars. The current esp-idf build is using more heap. Looking at reducing the dynamic buffers - also set to 16 top buffers when 10 in the past.

**Comment by gfwilliams** [comment] 2019-02-12 10:13
Normal Espruino builds actually allocate space for HTTPS out of JsVars and that was disabled for ESP32 - potentially that could be re-added I guess?

**Comment by jumjum123** [comment] 2019-02-12 10:24
@wilberforce, did you check minHeap in ESP32.getState ? 
In theory, this should show minimum size of free heap, happened sometime during execution
Idea was to use this to adjust number of jsvars
freeHeap is 37 kb, which is a lot.

**Comment by wilberforce** [comment] 2019-02-12 10:26
Ah - thanks - that explains it.
I think hat when @jumjum123 changed to use the esp-idf version on mbedTLS that was lost. This was due to the esp-odd version being several versions ahead of the version use in espruino and there where missing functions and it would not compile.

**Comment by wilberforce** [comment] 2019-02-12 10:29
@jumjum123 - I don't think free heap is that large on the current travis build - perhaps 32k.

I also recall there was a http so buffer size setting in espruino - as the desultory is something like 15k.

A bit more reseach!

**Comment by wilberforce** [comment] 2019-02-12 10:31
Sorry -'typos above that I can't correct on the Ipad!

**Comment by wilberforce** [comment] 2019-02-13 09:28
Looking at the available heap in the versions above v2 has much more heap than v3!

It looks like the callow used can be changed here:

https://github.com/espressif/esp-idf/blob/master/components/mbedtls/Kconfig

And the buffer size from 16k to 512 and also turn off suites not used to match the espruino/mdebtls/config.h

**Comment by MaBecker** [comment] 2019-03-07 21:21
@GabrielGab 
> but ESP8266 still working fine for https, on same version.

Nice, do you like to share some details using https with ESP8266?

**Comment by thedamian** [comment] 2019-08-25 21:52
I can confirm that this is a FIXED issue on v2.04 for BOTH ESP32 and ESP8266

I suggest this issue is marked "SOLVED"

This was the code I used in BOTH devices successfully.
Devices it was successfully tested on:
ESP8266:  D1 Mini &  NodeMcu Lua ESP8266 ESP-12F 
ESP32: ESP32-CAM , the LILYGO® TTGO & official expressif ESP32-WROOM-32D

Write up with screenshots and details is here: http://forum.espruino.com/conversations/330049/#comment14873565

```
var ssid = '***';
var password = '****';
var port = 80;
var wifi = require('Wifi');
console.log("started");
wifi.connect(ssid, {password: password}, function() {
    console.log('Connected to Wifi.  IP address is:', wifi.getIP().ip);
    var http = require('http');
    http.get("https://www.google.com", function(res) {
      res.on('data', function(data) {
        console.log(data);
      });
    });
    // wifi.save(); // Next reboot will auto-connect
});
```

**Comment by olliephillips** [comment] 2019-10-12 11:34
@wilberforce I see this in v2.04 on ESP32. I'm struggling to understand what the solution is from the issue thread, although it's closed. Are there any pointers you can provide?

**Comment by wilberforce** [comment] 2019-10-13 10:15
@olliephillips

With some sdk updates, related to ble, the mbedtls was switched from the esprunio version, for the esp-idf version. This was due to functions that the ble code used that was not in the espruino version( it is behind the esp-idf version). The espruino code was modified to use jsvars as memory buffers, so the current implementation is trying to allocated from the heap and there is not enough free memory for this.

**Comment by olliephillips** [comment] 2019-10-13 10:51
Appreciated. Thanks. So the standard builds not very useful for http. You do a custom build to get past this? Any tips? Sorry, I’m really late to the ESP32 - my first one landed this weekend. All flashed and connected, just not very useful as is :)

Sent from my iPhone

On 13 Oct 2019, at 11:15, wilberforce <notifications@github.com<mailto:notifications@github.com>> wrote:


@olliephillips<https://github.com/olliephillips>

With some sdk updates, related to ble, the mbedtls was switched from the esprunio version, for the esp-idf version. This was due to functions that the ble code used that was not in the espruino version( it is behind the esp-idf version). The espruino code was modified to use jsvars as memory buffers, so the current implementation is trying to allocated from the heap and there is not enough free memory for this.

**Comment by wilberforce** [comment] 2019-10-13 22:30
@olliephillips
You mean https? - it should be fine for http.

A work around for a custom build would be to reduce the number of jsvars, so that these is more heap space left.

**Comment by wilberforce** [comment] 2019-10-13 22:30
@olliephillips
You mean https? - it should be fine for http.

A work around for a custom build would be to reduce the number of jsvars, so that these is more heap space left.

**Comment by wilberforce** [comment] 2019-10-13 22:30
@olliephillips
You mean https? - it should be fine for http.

A work around for a custom build would be to reduce the number of jsvars, so that these is more heap space left.

**Comment by olliephillips** [comment] 2019-10-14 09:28
Sorry yes https. I’ll look at building with fewer jsvars. Thanks for your help @wilberforce

Sent from my iPhone

On 13 Oct 2019, at 23:30, wilberforce <notifications@github.com<mailto:notifications@github.com>> wrote:


@olliephillips<https://github.com/olliephillips>
You mean https? - it should be fine for http.

A work around for a custom build would be to reduce the number of jsvars, so that these is more heap space left.

**Comment by MaBecker** [comment] 2020-03-13 17:15
@olliephillips did you get https working? If yes please share your changes - thanks.

**Comment by olliephillips** [comment] 2020-03-13 17:34
Hey Mark, I didn't, no. I had a go at it, but quickly parked it I recollect, and I've not had much time to spend with Espruino recently.

**Comment by 23RoMax** [comment] 2020-05-17 09:40
@MaBecker I've tried it with three different heapsizes/heapvar configurations.

As you have [recommended here](https://github.com/espruino/Espruino/issues/1777#issuecomment-618232966):

` heapVars = (esp_get_free_heap_size() - 60000) / 16; `
--> HTTPS Calls are possible
--> **New issue I encountered:** mbedtls_ssl_handshake returned -0x4290

` heapVars = (esp_get_free_heap_size() - 65000) / 16; `
--> HTTPS Calls are possible
--> Same issue
--> Additionally: Memory warnings

` heapVars = (esp_get_free_heap_size() - 70000) / 16; `
--> Memory warnings, no connection to wifi has been established by my ESP32 (coincidence? - not sure if it is related)

Now that I got HTTPS working, I still can't make use of it due to the handshake error above.
Some [research suggested a memory leak](https://www.esp32.com/viewtopic.php?t=10330).

Did anyone encounter this issue and solve it?

**Comment by 23RoMax** [comment] 2020-05-24 16:40
Hi @MaBecker ,

any chance you would find a minute to have a look at my previous comment :) ? 
Highly appreciated to get a hint :)

**Comment by MaBecker** [comment] 2020-05-24 18:43
Hi 23RoMax,

sure,  please share the url that is causing the `mbedtls_ssl_handshake returned -0x4290`.

Your build is using this: heapVars = (esp_get_free_heap_size() - 70000) / 16;

Have you removed some modules ?

If you like we can chat over gitter.im.

**Comment by 23RoMax** [comment] 2020-05-24 22:01
Thank you!
I tried several RESTful APIs as I'm trying to extend my coin tracker.

The first endpoint I tried was `https://api.coinbase.com/v2/prices/BTC-EUR/buy`

Another one I am successfully using with http requests is: `https://api.coindesk.com/v1/bpi/currentprice/EUR.json` 

Also `https://google.com` yields the same result.

My latest build that seemed stable was with 
`heapVars = (esp_get_free_heap_size() - 60000) / 16;`

I noticed that anything higher caused issues and crashes.
Didn't remove any other modules. 

I don't have a gitter.im account yet, will set one up.

Thank you for your help!

**Comment by MaBecker** [comment] 2020-05-30 05:05
Ok, I also disabled the dynamic var allocation by commenting

https://github.com/espruino/Espruino/blob/808f7afae9f76032424295724c7bda95e927529f/boards/ESP32.py#L40

and set

https://github.com/espruino/Espruino/blob/808f7afae9f76032424295724c7bda95e927529f/boards/ESP32.py#L22

to 1800.

this will give you a very large heap space

**Comment by MaBecker** [comment] 2020-08-30 11:44
It is all about free heap space - best choice is to buy a ESP32 Wrover board because it has PSRAM.

**Closed by MaBecker** 2020-08-30 11:44 UTC
Labels: ESP32
